Repository avishka2k/find_food_application, pull requests merged in 2022-10, with the labels that each got.

#1 Food application theme and history page create and implementation
  lib/screens/history.dart
  lib/screens/home.dart
  lib/theme.dart
  pubspec.lock
  windows/flutter/generated_plugins.cmake
Labels: documentation, hacktoberfest-accepted

#2 Adding email file
  lib/screens/email.dart
Labels: bug, documentation, hacktoberfest-accepted

#3 Application login create and update
  lib/screens/nv/login.dart
Labels: documentation, hacktoberfest-accepted

#4 create forgot password
  lib/se/forgotp.dart
  lib/se/pwreser.dart
Labels: documentation, hacktoberfest-accepted

#8 create pkg
  lib/jn/pkg.dart
Labels: hacktoberfest-accepted
